---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBlwP7t08agboAVVhItmy3FQYMelJx3ai5gei9foPum6d5lULasp/4KWeXnXULCqy4N9Bxb/HW6oVAl3S/sUFuYKs25Tv56uOKX8JQxbny2Izr/ATj1wOmLV2ddoC4bHnCQEehsfUr+CfSezeir0afilWB39XP5xPmtVKp17mcKo9WoQgoqqPFzh2XXFYEdLz9yM5Pa0bN4idckv6RG4ZFNcNa4jSaRBgNoN+YAvhVX8DpHa8HlA/5oTZwAS+Qz0WSqBbm79VfWOBq+lkbpue0KqYGv7o0WHeZt0zxYcO65sUDGBENNjesT3XS1n2o4/3DAfWXeOTDWDzJaZbiLwo1peSZNIpN70v96H0kN7tdJNWOatmxPjDexd88BeVntqe9DyeK8/CdRFgqHr65+8B7RErZh2YWtTTDQwABIQX3jdr3ccD/8YJIDVojlTyY+AKQG+5GRWbRYA4RuxOu7L2qrdd/ieXJTY+uhjoNste0m1sxjO8RsuAe8y6MTvHiwelYmrVxo9SZPy9lcCMRIbDZhE+g2Odz5Qg2WQjNDDSfw8p/oWNbPthgtNbcscfEsvHN0UNQ7J6C3nx1r/Gzpr9qazKLxpRAuWhpkIEG4De+Zmcoh9S11qMyOlz6dX0K3MYU3Fsx6az1usyTV8FvGZmhf8PbHz02+opEwaq6epi6T12yTH0YAwpi3NfoKWBVxWMUSodm0ASb35uCI5Enqgn7xUSH2f/xDyUUQsz+sGPhU1A==
    admin-user: AgCCM3/d47wOSkfO7vsZoBVL1Hc7vRn+wDbjj59O+RhKh5wCODmO/Is3YE6gaFGsxHOGjErH0ygxRUsusKxzu8fX794xNeT6L2Hq2csDCDbayQSMtZyim57mRg9hF0JGSIhh1r2feTeo29lBSTXIAV0hBAo70lM4AIqyPD6SlbNZXGszWw9oNvxtZFQtHqxOHzKlvRjb0rzJmrzQoercfams46prgvyhdTvs841s9Gjmo5BtqJ8uvE6iB+qdhx/BcrNUFfBJUWtAlTW1VEulvZQP28wGH/7FFhKqat8NTZrJC5zhlDU/pihNyvtwkgVo9x9ZbW2u84CK2VGlOQ1Zgli7Vv84Pls7Clp4DrE1jfVYuVFGJDSRm1Wfl0/anHM/k8UaFl6ZbR2AZB6tQz0Ze7x6lJN/8sb1jjja2AcyLpr2lnwkvDunAWUwlu9cOO7OQ3WMldqOc1gSCyIuPWUrvVwknRPUcznxL6+durUt/qZL8g9iOy5SZ+XEgVtv3FfvuZlRzUy/+LhHz1wv2NS/YMket1qVkokRP4dgo2BTs8JZ36GXLe07pmBiSwnEbZ8BLffGVLSxLbZZJOBt9B87PeapjcnS2dklmn0GTZeNG+kkONj4FM5b9RzPdatVP4EfH3YtEc3JlgOgXHfpPRejkyE14DwhKxlIFKg7EtiUC5L+R38m9tlSJwt2aYVhc0Twx0Opt4iTXQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
