apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgAI/Xy9FB6wwDP7YVIbGIkUY24FLM6rwIto0Ipxz9vPdxnOtWH3Wd7KjZ5MXrK0zdZ7WVP7YOaRD1c1ECPrcicwsyHZT8F9wlFFUzO7iHCVcM3m93cCSwrmrifsxlkY6fALc6s/IxCUjxQ0nC3F4795AXkVSoADTo83owrSoN4I2+PBRVH81GjxAiD6gGsUu2Ie5I/IvA3J1Jqc6wF2ksZaPEYXG2EI67PLuesbm5KCysH/1AIgizZNSCaftHtzeUhy6TpwrfxVoAMPqVJx1DliC+isHtoxwWalwXBZOBBeyhu/WIWA4pA/GSzdv2ctoDrDBTvKNQsa04CEMpBB3jcf52989IJf3CbaTTRlobNAAiEjKhg+O05qHAkrz9awUOvvkrEgk3L1gOxZXgYykqwnrRabw8f8WuAuOnhF8b+gJ8bVH5ov4ITqWqxIrYUyWzC7ItYBdbViWZsMSNKj0xm3rxQ+A0pft85k1QKx/m2xZ8ZXN9mzsPjiNORIHR1tQ/vzRdxSri3gKGT7euBcoD6drqh9XdvHuj4fujoXNvoyDEalb9heMW2rdOQdA4Ad43kaBpYGD0ZfXegx4OR9y3+SPOvvq+MLuqjYwAuoA70QKQAq7DhIeuLJ3jl/1KoDJKvp0eR+HZV4eMpDSbV6l7B3/mthhXoVsBcqyJsG18kPb2Cb79g5+xP2rkqRHD+kijcrB8/2ZPCeZ+b9bMPDS49u6xv7ach3lw4FX35Wrn9MCQm38RlboteEmc7COvJniphRBmyUswAXCQKlHfcsTA==
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
