---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgCLa9a+3DgC2BKuqiDZJin8lPO0pi1nDhI51tyGbBbplmp18chJ9X09uAAu3MEBSTViXPLpagddMrrcazVgr24c7/qnGq0OHGn8//UFSVVlJvU4ObXLVN+Eze/64ZRb/W8AfbHAyKpHz2qoIyVKb/aGtefsA1LfauRqJqigofksdJdNNG2CLxKoUyFAIL6wlovD2cNC6g4ddqDzobTnVImOeNj+g5UBGiKx+cFDhcGhm5HGqfahvQ6nqxWS3H/pLq/967W7F3XUGQ4CWMxVxmaI5sset68jrb9Yo5BEVExZd7V+SEM2j+3i2CzQtIA0sSsOkYDaMuQHzxERhn1tnCnFPEcEW/xoKIE7+pkO35FmM3nPUZXqwILe+qvjYswELgT5/H2elyYM0cOZQ+2FcThLXQxOABY1VNcb/Aa7hlMSVqDh5rTJrjiTIB9QS1Ng6pw3traR3rohrViA1EqY2SvMDlORUsi3rw3nx8EuKtQrvQJpON45qGvWS42+MsthPYj9v/ZHX3eMYzzDvCx6mmMptMiv2r2JRT99C1O47zx6NU9Ipdzyoat0YHP8t8TEMNwB/8ppR8nCg/0N5lWV4jmQ4hJ5koi0QqY2DGKnIKOYGApYcP+fGVwAU2lzmpKc4R4C1nHG+JCZ7HR/0srScwlmXN+Lrq5WbQZGR5Ykb9eTPGcL0x9CwezIkyBZVqnUZgNj4+Gdh59Nqe69yGs9
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
