---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgCQOxk47SGjtue2gEe/IPythfkfahZu2o1Ip3eB7tZ6nqvcXeQRd2vOoKL52kJlf0o7sC0ijyJ0ZwM4DFifylp1GQ/i1yPqXAPDD0FPdyd2rFPGQTdPRfjXQE7CnhJw7ZWowblUP763Nl4sMO4xqldTytA2fiVbopdKTyMoTofYDVW1hIP8TxOpwzCko7EPvsss6Yt1KhAdAsv9wrGBWEr9AVEA5FIy/Dvg0aD3iBQXCluuqyzKIIF/hPCF5rYjafXpxXgsNCvX9oE4E+KVbHJ6tBwgldvC6pQP3NzIgE99USG3MYvgFtZb8H0fzbkCn3EqupCue8QFijqo8Z8raWQWzzHY9B6NKGc+V1ZXWCM/7FbsVxBEeRlEbT1vlz04xKdoHkzupw8uAi4e+HTOWT296d/Yt5jYw+VGxF3qVi0cF2CkIcEkmx25pBYcL7PwYzVXGecQihT4OROpIgNwiPOndZuS7TqlfwebBd87JWTmZSytql/knYWS8/t6R6PtwXgxPMml/u+A5Hnm76GjStpGtFqrcLB7rwdSIaYcjJoQSoo5cGdzmGuoIXczgr/ZfNTxH/awFu554maCqEj4YaSm7sjHYpQOppEdKicgIeHhnFJLRyYwtzq2UA+COH4GWFk75IXM3OdPOoBU/jvLGU6F7HIxZSdtokrPVsRlbIiCTC9tYidp8xX8LVuRuSDCagr7hs9glEvQue0ElajZpxfI
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
