---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-registration
  namespace: forgejo-runner
spec:
  encryptedData:
    token: AgB71a7qfX5EOoex8nsRL7ZW7Di/TxlTgn1eCTa2eNzzVYW35VeKEfiv/aZu4r8uSlRUGM8TUnhwZuRk6DU1bRSHf7VrUtrdnye0tXhcJzuLZZ+Xp9UOxxizxD0AC1OR5tVdPoRufJhF4cC8KPwWK6MxLeq2zSCtX/Nfl5VnqDNZGo1ULgoBdIPfSjJUAWX0TjJ6fb/JZ1AVV5jc6wyQx7FU7qkLYgu/PfuHQQW89PiYDVGcGMubSdk1Vxl+y0GnXVtQlJQ6AbxX85Qrm+Li626PPJ2jCp5173KWxtDr/pNjKNsr0uq1ZznoITgUd6QYmzYqDewkar1ibWALQQwRIrJO2ToPCZ+BqgXNr70/7doQrxUV0WEc449V/NtCvrKT5t7Y8ysVmwspDsFuc7dsNHTlhMH+LFtKAm51bG3wk3m2dLP0eh9RKWONFC8vh2LjoNINc8Ko8iwzeBuqCLFVCPtYFfbDJy0MbHJBbDcDU4deHuzxdHQULtT75aoSJbtkkks7+4KKhPRdlbYqkYWwNHTY8YOjLQnN7NgBivDX7JlCZs+saGtpotQgpRI6/sVw09Ah1M8Nvfy7JZW0X9WLJ0Y9KI6Ze245kBIJp56w94AV8NDuTgSlDlMhGzua+NlE6oM6Q8f0wX/3cJb1AszysmRDBSCOVLEARHNcWRXjQq762OceR0YsG7Ac3fW3iROCk94QRcsUVJ58c2wHS9H4LohJy/uSIZzryHDNBHaqFV0Hy5lzm5xb17fv
    uuid: AgCtc43HgDYXqAriOdkhaM92HgpOaFtQAgdOTr7kOokuVkqjli4JfGi1tEEq5jMzWPsiEuFZLY8/H3qgoKSyb7uPKdV+fhqrQD6X07wqeBn3jEdcJkwtHQw4XrFXx+YIiQBuOPsQyQ5RVBMDKHCuAgVG7ccQMdIFsW02kzgulzo5PC2VxVaDC3JHJtGT7xg2yo/L0st8YzSSY4e4nsCj9pqFNgYZSnakRUc4IWcbhbflvZfcZibOoOVcgrXaWPlVab9LKvmIhvdmzW6eCTdLCK+0HFQCkKpFaY9yMOtKBF0ENjRAy4CG15CbgACEChUa0DejfTxJdi0TKeQFSYe/1t8vXikSXKXnD+QDXbXyp5pWr4IF43G19YW3ZKAbXklbkddj0d7ZcFX3OIC/CV0O1UJdvZJZnKMTyzC7cCZMMLDR8NwGUDq9HxXDWlfFpZtreQWVavBDZvv8asOi1l6b60xj28OrCgGvb778u9Geo+0GtEHuLdCfj0D4ImYgc1hs2H6y2ZGfIAWZ2HllAM3im3OzWpk5vTK5PbiIgu1qkkfWrwb40rWfMrk56KtQ5x7mE59kN99zYAjJupf82vlhcum2/wJwgOXhpPRLbIUpaG8B07cFgTuwxNzhWKY2kaiFYilze7IkmPSQJo/dhrZm00R9TBZ8HP06AsNLxDb8oSmjuStjrsfqQdYNobE1FIJndisgWuDHcLlnto8A8kLoezCPhOYkAz0niy5Xa3wQ1GO0Hq1LZdI=
  template:
    metadata:
      name: forgejo-runner-registration
      namespace: forgejo-runner
