---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: finance-app-session
  namespace: finance-app
spec:
  encryptedData:
    SESSION_SECRET: AgCT785wqOYD05E+2aJYtXFRPuEn+QDf6HZ2QlVKx10xPk6vACNdq9mYamXeN/CZUZZTpFRBNHcYhhbmSsvmaLuF2Xxu+7oAxEOKi1D8FxYZQk/Z+2b0i20cYobnwESdDB6+3Fsrlcaz+9Axx0tdiiQ4E/E5uLoddZcG9HEnDVPKlof5lD639kigMSSRfgZ8PbkwWOZHb4F+2wxqOPPNgvWoRKGaGz1VXvZ2IqM2xKUZxMVTCx9/vTSEKNKCENc++Ia59lVYSkw0GtPlM1H164p1yN+7ff4tt5OIPvTTfVfKC7sScERAnlYrGNiTEdx0PQ5LSCV7WWAauvragmS4ScPU+wffMPn4PGsbrOvr0dKdKCdGhAVXVWkJ+75QkHRA4ctxQFZ63AvnwIXfJbjeaJW3JO/9VpSqNK6cuJlZsIyQHhqcYwfFlHvLiKLwxjbGxgG3J11Wrt2hwzDZSTg3VZ3do88Jz5+j27MQxNzC9ag4DaTbrgXel/USiYsEYqQ4tG6nRbZpa/TzeWddbSN4HrJOLYKStVFhSphilsvMbYpxjybJ+yBz3MLYEzsfYn+bUohZfYtlxj/hCn59KdZwWNc3Y6IGAyRNIrWX5tL/kimFfvA5pBSJlre2B5G0Bb9ax+tpw/m0wNZbReZtWgl985SF4qE04X6Wc/cUOOMm82vZ/CDvg2lWBKIEMbjx87B3w6yqngsX+6ZJ2CL0M5iX1x5momczckfkVNDZuV5FIIpdqBzjMMFtz0tyNxNu
  template:
    metadata:
      name: finance-app-session
      namespace: finance-app
