apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - configmap-buildkitd.yaml
  - deployment-buildkitd.yaml
  - service-buildkitd.yaml
  - secrets
