apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-security
  namespace: forgejo
spec:
  encryptedData:
    SECRET_KEY: AgAe8bU6yu+QHTyIP2OKqUOn4pGp3pqQjvj8l+3PypZJPn6sRzg8qQ2oKRa+WDKakfrbzDCNSr0QIf8LtYJp6z4yLnXOnoN9MOovYxGF7kQEakwlZ/jko4YtE3G4FAnFsAuvelYKHa3qhaeS0TugFlY0z2l2vPnXUBPX1a2Y3wSjjIOVMZ40PRg4CHNcStbFEhPV+DevkZDmL8kulSFWOEGQ1e0QeffM4V5cHo3jg3HEYQa1UKG36tmz77U70HBzXtnvEBo6NHTLmHAFIHCtpqT+J2aj4tef3XmMvXZ0OSzB9M0QKAOQd9CgBMQKNGjQbSPZYTo3CoCftb9Su80ci1JK1wUK9JZyg8jJx6ZjqRq/ySG1QFq5I1hQYoLIFBZNRHAT3tViKEzG5HmMDypeNPs9Uh5SV9fplAODwy3PlL9VdMxT39ZCAFbzkLGgBhIh2Zjq5DdkYh8cci68BK727Op+e07nNd2zPVsrdhW88yH29tq5OZwb4ReAGsyGaPdSR7NOnqnsyZzho6E/g4SK3DtEjk3PkZBmO/MAh67+3lxNOpyyRobYKdpXL9mz8mi+FuYTvf3Z7BBuui16kClO/WHizZIPIwy1rNZ7cO/i2mOjDNC1+dkhDCdcoqc6XXO06x+TJtso4PSurpWTfdYQwaezmKsLEJXK2oD3xRg0ZyOPDVCIfvrQ9LE1jhb3MQN63fV0fUZesVF+mq8IB7xriL6glYtRb58ZRcXuQkgVrsNqabBHwmhUjh0A+pjx7LMp7VIxyIBxetkD54zj+U9yibwo
  template:
    metadata:
      name: forgejo-security
      namespace: forgejo
