apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jddemonteverde/homelab33.git
    targetRevision: main
    path: infra/tailscale-proxy/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
