apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAMDoFuwE0gJongQ/QanDip/RIsxBFC70v5lfH0Ot+3Dbt/1agM7jTNajm3HGPkNv7OS74rCrxbIf4dhgOZaNHlkc9I8m9gf6Aw9w86WJ6Hq3yz92c3KbDYFzoLzi+IPqQXW1qtMhSU5bVTj7WV2iYp4mMfrcjAjVKyd1jtTCUtSMSPhgqvsstZtVnO8Pk0y1OukaFp/C4g+nk6r89X39A8R6g8lghfNhhj/SaV8tFwslEyjEyeuYcaV8cU2m/ORPVNJo0MtSBBhej2qGI9aIn3FB0SFqD2MfglBGpzCROqEdxPn7pe5lk7LWy4uIFNLnhlSMXlDPqAOArDwow0bHQ2fX8WhVP/vX9dTEZHyGyPkVKjdj5/SCgO1laBJpkPRts2+7oXWRrz4HIMhC15PpRKr4f1Hc8x5B2NDQsMSWJCV0jRcRNxyZ+sNFz4I9dKs/F7Uf65beaHuyPm0QNi7WvqSC4jtLK0+LYfjR2YQl8cHR3cW3SsC3lpLXfGfPaZfwuKq56IhNauuEP8X1HLhCa0uc2meIIHcNIS715mkUSnTzho0UKnBdbFkt4GCVbod/SB5ruRkFdWL23w44rL3B5nDh5UFS0I4rJh8do7K4kU/6W1ZVukgaZ8f3V1++q2e9rho3+gUUIbfriBgj/S3Z0++wy6c92l6V4nmAm+XBqstmPDzuPEoEMMfFvI7lZlG4slXWtusYOWRdWTRjpQNyzQla51BQ8F4XCRj+tSiNQZuuWOnXwWQmQXbTwZqJRJr8xpBU+2wA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
