apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finance-app-data
  namespace: finance-app
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
